<?php

namespace Krs\StateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContinentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContinentsRepository extends EntityRepository
{
}
